### PR TITLE
[#62] Support GHC 9.2

### LINKED ISSUE #62: Support GHC 9.2

### PR DESCRIPTION
**Pull request by chshersh**
Resolves #62

### CODE REVIEW

**Comment by chshersh** [comment]
Currently blocked by:

* https://github.com/hedgehogqa/haskell-hedgehog/pull/436

**Comment by sjakobi** [comment]
Please note that the latest `hedgehog` release is compatible with GHC 9.2.

**Comment by chshersh** [comment]
I think this should be good to merge once CI passes 🍏

**Comment by the-dr-lazy** [comment]
Shall we go to heaven?

**Review by vrom911 — APPROVED** [review]

**Pull request merged**
